name: Deploy

on: push

jobs:
  dev-test:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: This is dev-test job.
        run: |
          echo $MY_VAR
