name: Unit Test CI

on: push

jobs:
  unit-test:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Try to fail
        run: exit 1
      - name: Print a greeting
        env:
          MY_VAR: This is unit-test job.
        run: |
          echo $MY_VAR
